### ISSUE TITLE
The goal and guide does not match at all.

### ISSUE THREAD

**Issue by badgehunter** [awesomepandapig/skyblock.bingo#4]
The tasks in tier matches, as does their difficulty ranking. the goal thing matches but then when you start clicking tiles at board , it shows previous bingo's guide with current bingo title&goal. like for example attached picture shows cocoa beans collector, it says to get 185k cocoa beans, and then the guide is to get carried in dungeons... copy pasted text incase picture does not load

Cocoa Beans Collector
Reach 185,000 Cocoa Beans Collection

Have someone carry you in dungeons.

You can find people to carry you in [URL='https://discord.gg/bingobrewers']Bingo Brewers[/URL]. You may be able to complete this with Party Finder if you cannot find anyone to carry you. Doing this during Paul's cycle during Jerry may be easier.

at the board it shows also previous bingos community coals but at bottom where it says the tier numbers are the correct community goals.

![image](https://github.com/awesomepandapig/skyblock.bingo/assets/31507359/238488e1-a769-4625-8107-e7578a03abd8)

**Comment by awesomepandapig** [comment]
Sorry about that. Guide data is not automatically added (because it's hand-written). I was away for a bit and hadn't had a chance to update the guide. It should now have this month's goals (you might need to clear your cache).
