### ISSUE TITLE
Legacy Bingo Event API Data Request

### ISSUE THREAD

**Issue by HacktheTime** [awesomepandapig/skyblock.bingo#5]
Hey I'm searching for all the previous Bingo Events Data. If you have them still in log perhaps it would be great if you could make them available for me.

**Comment by awesomepandapig** [comment]
I have no idea what you mean by "Bingo Events Data". If you're looking for historical goals you can take a look here: https://hypixel-skyblock.fandom.com/wiki/Bingo/Events. As for player data it's all pulled from the Hypixel API.

**Comment by HacktheTime** [comment]
I mean the /v2/resources/skyblock/bingo for the previous events since that one only shows the data for the last / ongoing bingo. I was a wondering if you have some of the previous bingos data from that api still somewhere.

Fandom is missing so!me of the data like the internal ids

**Comment by awesomepandapig** [comment]
All righty well unfortunately I do not have that data saved.
